/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.sistemaGestao.JFrames;

import br.senai.sc.JPainels.CadastrarTarefaEquipe;
import br.senai.sc.JPainels.CadastroTarefas;
import br.senai.sc.JPainels.EditarTarefa;
import br.senai.sc.JPainels.ListaTarefas;
import br.senai.sc.JPainels.RemoverTarefa;
import java.awt.CardLayout;

/**
 *
 * @author Kathu
 */
public class ColaboradorJFrame extends javax.swing.JFrame {

     private CardLayout cl;

    public ColaboradorJFrame() {
        initComponents();
        
        this.cl = (CardLayout) painelPrincipalCol.getLayout();
        painelPrincipalCol.add(painelMenuCol, "painelMenuCol");
        this.cl.show(painelPrincipalCol, "painelMenuCol");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMenuCol = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        ButtonEditarTarefa = new javax.swing.JButton();
        buttonTarefaC = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        buttonRemoveTarefa = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        ButtonListar = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        painelPrincipalCol = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jVoltar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton1.setText("Cadastrar Tarefa para Equipe");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        ButtonEditarTarefa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonEditarTarefa.setText("Editar Tarefa");
        ButtonEditarTarefa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonEditarTarefaMouseClicked(evt);
            }
        });

        buttonTarefaC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonTarefaC.setText("Cadastrar Tarefa");
        buttonTarefaC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonTarefaCMouseClicked(evt);
            }
        });
        buttonTarefaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTarefaCActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro");

        buttonRemoveTarefa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonRemoveTarefa.setText("Remover Tarefa");
        buttonRemoveTarefa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRemoveTarefaMouseClicked(evt);
            }
        });

        ButtonListar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonListar.setText("Listar Tarefas");
        ButtonListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonListarMouseClicked(evt);
            }
        });
        ButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Editar");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Listar");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Remover");

        javax.swing.GroupLayout painelMenuColLayout = new javax.swing.GroupLayout(painelMenuCol);
        painelMenuCol.setLayout(painelMenuColLayout);
        painelMenuColLayout.setHorizontalGroup(
            painelMenuColLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
            .addGroup(painelMenuColLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelMenuColLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(painelMenuColLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(painelMenuColLayout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addGroup(painelMenuColLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(71, 71, 71)
                            .addGroup(painelMenuColLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painelMenuColLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buttonTarefaC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jToggleButton1)
                                    .addComponent(ButtonEditarTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(buttonRemoveTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE))
                        .addComponent(jSeparator3))
                    .addContainerGap()))
        );
        painelMenuColLayout.setVerticalGroup(
            painelMenuColLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
            .addGroup(painelMenuColLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelMenuColLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(painelMenuColLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelMenuColLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jLabel1))
                        .addGroup(painelMenuColLayout.createSequentialGroup()
                            .addComponent(buttonTarefaC)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(painelMenuColLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonEditarTarefa)
                        .addComponent(jLabel2))
                    .addGap(18, 18, 18)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)
                    .addGroup(painelMenuColLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonListar))
                    .addGap(37, 37, 37)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(painelMenuColLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(buttonRemoveTarefa))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        painelPrincipalCol.setLayout(new java.awt.CardLayout());

        jVoltar.setText("voltar");
        jVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVoltarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jVoltar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painelPrincipalCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelMenuCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painelPrincipalCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelMenuCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTarefaCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTarefaCMouseClicked
        CadastroTarefas ct = new CadastroTarefas();
        painelPrincipalCol.add(ct, "CadastroTarefas");
        this.cl.show(painelPrincipalCol, "CadastroTarefas");
    }//GEN-LAST:event_buttonTarefaCMouseClicked

    private void buttonTarefaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTarefaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTarefaCActionPerformed

    private void ButtonEditarTarefaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEditarTarefaMouseClicked
        EditarTarefa et = new EditarTarefa();
        painelPrincipalCol.add(et, "EditarTarefa");
        this.cl.show(painelPrincipalCol, "EditarTarefa");
    }//GEN-LAST:event_ButtonEditarTarefaMouseClicked

    private void ButtonListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonListarMouseClicked
        ListaTarefas lt = new ListaTarefas();
        painelPrincipalCol.add(lt, "ListaTarefas");
        this.cl.show(painelPrincipalCol, "ListaTarefas");
    }//GEN-LAST:event_ButtonListarMouseClicked

    private void ButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonListarActionPerformed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        CadastrarTarefaEquipe cte = new CadastrarTarefaEquipe();
        painelPrincipalCol.add(cte, "CadastrarTarefaEquipe");
        this.cl.show(painelPrincipalCol, "CadastrarTarefaEquipe");

    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void buttonRemoveTarefaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRemoveTarefaMouseClicked
        RemoverTarefa rt = new RemoverTarefa();
        painelPrincipalCol.add(rt, "RemoverTarefa");
        this.cl.show(painelPrincipalCol, "RemoverTarefa");
    }//GEN-LAST:event_buttonRemoveTarefaMouseClicked

    private void jVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVoltarMouseClicked
        this.cl.show(painelPrincipalCol, "painelMenuCol");
    }//GEN-LAST:event_jVoltarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColaboradorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColaboradorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColaboradorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColaboradorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColaboradorJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEditarTarefa;
    private javax.swing.JToggleButton ButtonListar;
    private javax.swing.JButton buttonRemoveTarefa;
    private javax.swing.JButton buttonTarefaC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JMenu jVoltar;
    private javax.swing.JPanel painelMenuCol;
    private javax.swing.JPanel painelPrincipalCol;
    // End of variables declaration//GEN-END:variables
}
