/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.sistemaGestao.JFrames;


import br.senai.sc.JPainels.CadastrarEquipeJPanel;
import br.senai.sc.JPainels.CadastroTarefas;
import java.awt.CardLayout;


/**
 *
 * @author Aluno
 */
public class GestorJFrame extends javax.swing.JFrame {

    private CardLayout cl;

    public GestorJFrame() {
        initComponents();

        this.cl = (CardLayout) painelPrincipal.getLayout();
        painelPrincipal.add(painelMenu, "painelMenu");
        this.cl.show(painelPrincipal, "painelMenu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        buttonRemoveEquipe2 = new javax.swing.JButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        buttonRemoveCol2 = new javax.swing.JButton();
        ButtonListar2 = new javax.swing.JToggleButton();
        buttonRemoveTarefa2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        buttonTarefaC2 = new javax.swing.JButton();
        ButtonEditarTarefa2 = new javax.swing.JButton();
        buttonListarColaborador2 = new javax.swing.JButton();
        buttonListarEquipe2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        buttonEditarColaborador2 = new javax.swing.JButton();
        buttonEditarEquipe2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        buttonCadastroEquipe2 = new javax.swing.JButton();
        buttonCadastro2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jVoltar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPrincipal.setLayout(new java.awt.CardLayout());

        buttonRemoveEquipe2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonRemoveEquipe2.setText("Remover Equipe");

        jToggleButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton3.setText("Cadastrar Tarefa para Equipe");

        buttonRemoveCol2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonRemoveCol2.setText("Remover Colaborador");

        ButtonListar2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonListar2.setText("Listar Tarefas");

        buttonRemoveTarefa2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonRemoveTarefa2.setText("Remover Tarefa");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Remover");

        buttonTarefaC2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonTarefaC2.setText("Cadastrar Tarefa");
        buttonTarefaC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonTarefaC2MouseClicked(evt);
            }
        });

        ButtonEditarTarefa2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonEditarTarefa2.setText("Editar Tarefa");

        buttonListarColaborador2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonListarColaborador2.setText("Listar Colaboradores");

        buttonListarEquipe2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonListarEquipe2.setText("Listar Equipe");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Listar");

        buttonEditarColaborador2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonEditarColaborador2.setText("Editar Colaborador");

        buttonEditarEquipe2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonEditarEquipe2.setText("Editar Equipe");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Editar");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Cadastro");

        buttonCadastroEquipe2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonCadastroEquipe2.setText("Cadastrar Equipe");
        buttonCadastroEquipe2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCadastroEquipe2MouseClicked(evt);
            }
        });

        buttonCadastro2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonCadastro2.setText("Cadastrar Colaborador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonListarEquipe2)
                            .addComponent(ButtonListar2)
                            .addComponent(buttonListarColaborador2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel12)
                                .addGap(29, 29, 29)
                                .addComponent(buttonRemoveTarefa2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(buttonRemoveEquipe2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(buttonRemoveCol2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonCadastro2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonTarefaC2)
                                    .addComponent(buttonCadastroEquipe2)
                                    .addComponent(jToggleButton3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buttonEditarEquipe2)
                                            .addComponent(ButtonEditarTarefa2)
                                            .addComponent(buttonEditarColaborador2))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(buttonCadastroEquipe2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonTarefaC2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(buttonEditarEquipe2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonEditarTarefa2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEditarColaborador2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCadastro2)
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(buttonRemoveTarefa2)
                    .addComponent(buttonListarEquipe2)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRemoveEquipe2)
                    .addComponent(buttonListarColaborador2))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRemoveCol2)
                    .addComponent(ButtonListar2))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jVoltar.setText("voltar");
        jVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVoltarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jVoltar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVoltarMouseClicked
        this.cl.show(painelPrincipal, "painelMenu");
    }//GEN-LAST:event_jVoltarMouseClicked

    private void buttonCadastroEquipe2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCadastroEquipe2MouseClicked
        CadastrarEquipeJPanel ce = new CadastrarEquipeJPanel();
        painelPrincipal.add(ce, "CadastrarEquipeJPanel");
        this.cl.show(painelPrincipal, "CadastrarEquipeJPanel");
    }//GEN-LAST:event_buttonCadastroEquipe2MouseClicked

    private void buttonTarefaC2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTarefaC2MouseClicked
       CadastroTarefas ct = new CadastroTarefas();
       painelPrincipal.add(ct, "CadastroTarefas");
        this.cl.show(painelPrincipal, "CadastroTarefas");
    }//GEN-LAST:event_buttonTarefaC2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEditarTarefa;
    private javax.swing.JButton ButtonEditarTarefa1;
    private javax.swing.JButton ButtonEditarTarefa2;
    private javax.swing.JToggleButton ButtonListar;
    private javax.swing.JToggleButton ButtonListar1;
    private javax.swing.JToggleButton ButtonListar2;
    private javax.swing.JButton buttonCadastro;
    private javax.swing.JButton buttonCadastro1;
    private javax.swing.JButton buttonCadastro2;
    private javax.swing.JButton buttonCadastroEquipe;
    private javax.swing.JButton buttonCadastroEquipe1;
    private javax.swing.JButton buttonCadastroEquipe2;
    private javax.swing.JButton buttonEditarColaborador;
    private javax.swing.JButton buttonEditarColaborador1;
    private javax.swing.JButton buttonEditarColaborador2;
    private javax.swing.JButton buttonEditarEquipe;
    private javax.swing.JButton buttonEditarEquipe1;
    private javax.swing.JButton buttonEditarEquipe2;
    private javax.swing.JButton buttonListarColaborador;
    private javax.swing.JButton buttonListarColaborador1;
    private javax.swing.JButton buttonListarColaborador2;
    private javax.swing.JButton buttonListarEquipe;
    private javax.swing.JButton buttonListarEquipe1;
    private javax.swing.JButton buttonListarEquipe2;
    private javax.swing.JButton buttonRemoveCol;
    private javax.swing.JButton buttonRemoveCol1;
    private javax.swing.JButton buttonRemoveCol2;
    private javax.swing.JButton buttonRemoveEquipe;
    private javax.swing.JButton buttonRemoveEquipe1;
    private javax.swing.JButton buttonRemoveEquipe2;
    private javax.swing.JButton buttonRemoveTarefa;
    private javax.swing.JButton buttonRemoveTarefa1;
    private javax.swing.JButton buttonRemoveTarefa2;
    private javax.swing.JButton buttonTarefaC;
    private javax.swing.JButton buttonTarefaC1;
    private javax.swing.JButton buttonTarefaC2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JMenu jVoltar;
    private javax.swing.JPanel painelMenu;
    private javax.swing.JPanel painelMenu1;
    private javax.swing.JPanel painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
