/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.JPainels;

import br.senai.sc.sisGestao.modelo.CadastrarTarefa;
import br.senai.sc.sisloja.dao.AgendaDao;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class ListaTarefas extends javax.swing.JPanel {

    /**
     * Creates new form ListaTarefas
     */
    public ListaTarefas() {
        initComponents();
        popularTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTarefa = new javax.swing.JScrollPane();
        tblTarefa = new javax.swing.JTable();

        tblTarefa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código da Tarefa", "Data de criação", "Titulo", "Descrição", "Data de entrega", "Código do colaborador atribuido", "Código da equipe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollTarefa.setViewportView(tblTarefa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    private void popularTabela() {
        AgendaDao cd = new AgendaDao();
        List<CadastrarTarefa> listarTarefa;

        try {
            listarTarefa = cd.listarTarefas();

            DefaultTableModel model = (DefaultTableModel) tblTarefa.getModel();
            List<Object> lista = new ArrayList<Object>();
          
            for (int i = 0; i < listarTarefa.size(); i++) {
                CadastrarTarefa ct = listarTarefa.get(i);
                lista.add(new Object[]{ct.getCodTarefa(), ct.getDataCriacao(), ct.getTitulo(),
                ct.getDescricao(), ct.getData(), ct.getCodCol(), ct.getCodEq()});
            }

            for (int idx = 0; idx < lista.size(); idx++) {
                model.addRow((Object[]) lista.get(idx));
            }
        } catch (SQLException ex) {
            String msg = "Ocorreu um erro ao obter as tarefas do banco de dados!";
            JOptionPane.showMessageDialog(null, msg);
            Logger.getLogger(ListaTarefas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollTarefa;
    private javax.swing.JTable tblTarefa;
    // End of variables declaration//GEN-END:variables
}
